const QUESTIONS = [
  {
    id: "nts-001",
    prompt: "A serverless compute service that runs event-triggered code without provisioning or managing servers, supporting HTTP triggers, timers, queues and more.",
    answers: ["Azure Functions", "Functions"],
    hint: "Think events → code, no servers",
    difficulty: "easy",
  },
  {
    id: "nts-002",
    prompt: "A fully managed, globally distributed NoSQL database supporting multiple APIs including SQL, MongoDB, Cassandra, Gremlin and Table Storage.",
    answers: ["Azure Cosmos DB", "Cosmos DB"],
    hint: "Named after something astronomical",
    difficulty: "easy",
  },
  {
    id: "nts-003",
    prompt: "Microsoft's cloud-based identity and access management service, providing single sign-on, multi-factor authentication and conditional access policies.",
    answers: ["Azure Active Directory", "Azure AD", "Microsoft Entra ID", "Entra ID", "AAD"],
    hint: "The identity backbone of Microsoft 365",
    difficulty: "easy",
  },
  {
    id: "nts-004",
    prompt: "A platform-as-a-service offering for hosting web applications, REST APIs and mobile back ends without managing the underlying infrastructure.",
    answers: ["Azure App Service", "App Service"],
    hint: "PaaS web hosting — no VM management",
    difficulty: "easy",
  },
  {
    id: "nts-005",
    prompt: "A cloud service for securely storing and tightly controlling access to secrets, encryption keys, API keys, passwords and certificates.",
    answers: ["Azure Key Vault", "Key Vault"],
    hint: "Like a safe for your secrets",
    difficulty: "easy",
  },
  {
    id: "nts-006",
    prompt: "A layer 7 load balancer that provides a built-in CDN, caching, global anycast routing, SSL offloading and automatic failover across Microsoft's global edge network.",
    answers: ["Azure Front Door", "Front Door", "AFD"],
    hint: "The main entry point to your global app",
    difficulty: "medium",
  },
  {
    id: "nts-007",
    prompt: "A managed Kubernetes container orchestration service that automates the deployment, scaling and management of containerised applications.",
    answers: ["Azure Kubernetes Service", "AKS"],
    hint: "Managed K8s on Azure",
    difficulty: "medium",
  },
  {
    id: "nts-008",
    prompt: "A fully managed enterprise message broker with queues and publish-subscribe topics, used to decouple applications and services.",
    answers: ["Azure Service Bus", "Service Bus"],
    hint: "Enterprise messaging — queues and topics",
    difficulty: "medium",
  },
  {
    id: "nts-009",
    prompt: "A fully managed PaaS service that provides secure RDP and SSH connectivity to virtual machines directly in the Azure portal, without requiring public IP addresses on the VMs.",
    answers: ["Azure Bastion", "Bastion"],
    hint: "A fortified jump host you never have to manage",
    difficulty: "medium",
  },
  {
    id: "nts-010",
    prompt: "A cloud platform for creating and running automated workflows that integrate apps, data, services and systems using a visual designer with little or no code.",
    answers: ["Azure Logic Apps", "Logic Apps"],
    hint: "Like Power Automate but for developers",
    difficulty: "medium",
  },
  {
    id: "nts-011",
    prompt: "A hybrid integration platform for publishing, securing, transforming and monitoring APIs across cloud and on-premises environments.",
    answers: ["Azure API Management", "API Management", "APIM"],
    hint: "The gateway in front of all your APIs",
    difficulty: "medium",
  },
  {
    id: "nts-012",
    prompt: "A dedicated private network connection between your on-premises infrastructure and Azure datacenters that bypasses the public internet entirely.",
    answers: ["Azure ExpressRoute", "ExpressRoute"],
    hint: "A private highway to Azure",
    difficulty: "hard",
  },
  {
    id: "nts-013",
    prompt: "A DNS-based global traffic routing service that distributes traffic to services across Azure regions using methods such as priority, weighted, geographic and performance.",
    answers: ["Azure Traffic Manager", "Traffic Manager"],
    hint: "Routes users to the best endpoint using DNS",
    difficulty: "hard",
  },
  {
    id: "nts-014",
    prompt: "A layer 7 application delivery controller providing SSL termination, URL-based routing, cookie-based session affinity and a built-in web application firewall for regional workloads.",
    answers: ["Azure Application Gateway", "Application Gateway"],
    hint: "Like Front Door, but regional not global",
    difficulty: "hard",
  },
  {
    id: "nts-015",
    prompt: "A managed wide-area networking service that consolidates branch-to-branch, branch-to-Azure and VNet connectivity into a single operational interface using a hub-and-spoke model.",
    answers: ["Azure Virtual WAN", "Virtual WAN", "vWAN"],
    hint: "One hub to connect all your branches and VNets",
    difficulty: "hard",
  },
];

export default QUESTIONS;
