const QUESTIONS = [

  // ── Azure services ──────────────────────────────────────────────
  {
    id: "nts-001",
    prompt: "A serverless compute service that runs event-triggered code without provisioning or managing servers, supporting HTTP triggers, timers, queues and more.",
    answers: ["Azure Functions", "Functions"],
    hint: "Think: events → code, no servers",
    difficulty: "easy",
  },
  {
    id: "nts-002",
    prompt: "A fully managed, globally distributed NoSQL database supporting multiple APIs including SQL, MongoDB, Cassandra, Gremlin and Table Storage.",
    answers: ["Azure Cosmos DB", "Cosmos DB"],
    hint: "Named after something astronomical",
    difficulty: "easy",
  },
  {
    id: "nts-003",
    prompt: "A platform-as-a-service offering for hosting web applications, REST APIs and mobile back ends without managing the underlying infrastructure.",
    answers: ["Azure App Service", "App Service"],
    hint: "PaaS web hosting — no VM management",
    difficulty: "easy",
  },
  {
    id: "nts-004",
    prompt: "A cloud service for securely storing and tightly controlling access to secrets, encryption keys, API keys, passwords and certificates.",
    answers: ["Azure Key Vault", "Key Vault"],
    hint: "A digital safe for secrets and keys",
    difficulty: "easy",
  },
  {
    id: "nts-005",
    prompt: "A layer 7 load balancer that provides a built-in CDN, caching, global anycast routing, SSL offloading and automatic failover across Microsoft's global edge network.",
    answers: ["Azure Front Door", "Front Door", "AFD"],
    hint: "The entry point to your global app",
    difficulty: "medium",
  },
  {
    id: "nts-006",
    prompt: "A managed Kubernetes container orchestration service that automates the deployment, scaling and management of containerised applications.",
    answers: ["Azure Kubernetes Service", "AKS"],
    hint: "Managed K8s on Azure",
    difficulty: "medium",
  },
  {
    id: "nts-007",
    prompt: "A fully managed PaaS service that provides secure RDP and SSH connectivity to virtual machines directly in the Azure portal, without requiring public IP addresses on the VMs.",
    answers: ["Azure Bastion", "Bastion"],
    hint: "A managed jump host you never touch",
    difficulty: "medium",
  },
  {
    id: "nts-008",
    prompt: "A dedicated private network connection between your on-premises infrastructure and Azure datacenters that bypasses the public internet entirely.",
    answers: ["Azure ExpressRoute", "ExpressRoute"],
    hint: "A private highway to Azure",
    difficulty: "hard",
  },
  {
    id: "nts-009",
    prompt: "A DNS-based global traffic routing service that distributes traffic to services across Azure regions using methods such as priority, weighted, geographic and performance.",
    answers: ["Azure Traffic Manager", "Traffic Manager"],
    hint: "Routes users to the best endpoint using DNS",
    difficulty: "hard",
  },
  {
    id: "nts-010",
    prompt: "A layer 7 application delivery controller providing SSL termination, URL-based routing, cookie-based session affinity and a built-in web application firewall for regional workloads.",
    answers: ["Azure Application Gateway", "Application Gateway"],
    hint: "Like Front Door, but regional not global",
    difficulty: "hard",
  },

  // ── Azure Blob Storage access tiers ────────────────────────────
  {
    id: "nts-011",
    prompt: "The Azure Blob Storage access tier designed for data that is accessed frequently. It has the highest storage cost but the lowest access cost.",
    answers: ["Hot", "Hot tier"],
    hint: "Frequently accessed = this temperature",
    difficulty: "easy",
  },
  {
    id: "nts-012",
    prompt: "The Azure Blob Storage access tier for data that is infrequently accessed and stored for at least 30 days. Lower storage cost than Hot, higher access cost.",
    answers: ["Cool", "Cool tier", "Cold", "Cold tier"],
    hint: "Not quite hot, not quite frozen",
    difficulty: "easy",
  },
  {
    id: "nts-013",
    prompt: "The Azure Blob Storage access tier for rarely accessed data stored for at least 180 days. Lowest storage cost but data must be rehydrated before it can be read.",
    answers: ["Archive", "Archive tier"],
    hint: "Long-term, rarely touched — requires rehydration",
    difficulty: "easy",
  },

  // ── Storage redundancy ──────────────────────────────────────────
  {
    id: "nts-014",
    prompt: "The Azure Storage redundancy option that replicates data three times within a single datacentre in the primary region. Lowest cost, no zone or region protection.",
    answers: ["Locally redundant storage", "LRS"],
    hint: "Three copies, one building",
    difficulty: "medium",
  },
  {
    id: "nts-015",
    prompt: "The Azure Storage redundancy option that replicates data synchronously across three availability zones in the primary region, protecting against datacenter-level failures.",
    answers: ["Zone-redundant storage", "ZRS"],
    hint: "Three zones, one region",
    difficulty: "medium",
  },
  {
    id: "nts-016",
    prompt: "The Azure Storage redundancy option that replicates data to a secondary region hundreds of miles away, providing protection against a full regional outage.",
    answers: ["Geo-redundant storage", "GRS"],
    hint: "Two regions, no read access to the secondary",
    difficulty: "medium",
  },
  {
    id: "nts-017",
    prompt: "The Azure Storage redundancy option that replicates to a secondary region AND allows read access from that secondary region, enabling higher read availability.",
    answers: ["Read-access geo-redundant storage", "RA-GRS"],
    hint: "Like GRS but you can read from the backup region",
    difficulty: "hard",
  },

  // ── Cloud service models ────────────────────────────────────────
  {
    id: "nts-018",
    prompt: "The cloud service model where the provider manages everything — hardware, OS, middleware and application. The customer only uses the software through a browser.",
    answers: ["SaaS", "Software as a Service"],
    hint: "Microsoft 365, Salesforce, Gmail",
    difficulty: "easy",
  },
  {
    id: "nts-019",
    prompt: "The cloud service model where the provider manages the hardware, OS and runtime. The customer deploys and manages their own applications and data.",
    answers: ["PaaS", "Platform as a Service"],
    hint: "Azure App Service, Azure SQL Database",
    difficulty: "easy",
  },
  {
    id: "nts-020",
    prompt: "The cloud service model where the provider manages only the physical hardware and virtualisation layer. The customer manages everything from the OS upward.",
    answers: ["IaaS", "Infrastructure as a Service"],
    hint: "Azure VMs — you manage the OS, middleware and apps",
    difficulty: "easy",
  },

  // ── Azure tools and governance ──────────────────────────────────
  {
    id: "nts-021",
    prompt: "The free Azure service that analyses your resources and provides personalised best practice recommendations across cost, security, reliability, operational excellence and performance.",
    answers: ["Azure Advisor", "Advisor"],
    hint: "Think of it as a personal Azure consultant",
    difficulty: "easy",
  },
  {
    id: "nts-022",
    prompt: "The Azure tool that lets you estimate the monthly cost of Azure resources before you deploy them, by selecting services and configuring their settings.",
    answers: ["Azure Pricing Calculator", "Pricing Calculator"],
    hint: "Used before you deploy to estimate spend",
    difficulty: "easy",
  },
  {
    id: "nts-023",
    prompt: "The Azure tool that helps you calculate potential savings from migrating on-premises workloads to Azure by comparing current on-premises costs against projected Azure costs.",
    answers: ["Total Cost of Ownership Calculator", "TCO Calculator", "Azure TCO Calculator"],
    hint: "Compares on-premises vs Azure costs to show savings",
    difficulty: "medium",
  },
  {
    id: "nts-024",
    prompt: "The Azure service that lets you define, assign and manage policies to enforce organisational rules and assess compliance across all your resources at scale.",
    answers: ["Azure Policy", "Policy"],
    hint: "Governance guardrails for your entire Azure estate",
    difficulty: "easy",
  },
  {
    id: "nts-025",
    prompt: "The Azure feature that lets you group multiple Azure subscriptions under a single billing account and management hierarchy, applying policies and access control at scale.",
    answers: ["Management Groups", "Azure Management Groups"],
    hint: "One level above subscriptions in the hierarchy",
    difficulty: "medium",
  },

  // ── Azure support plans ─────────────────────────────────────────
  {
    id: "nts-026",
    prompt: "The Azure support plan included free for all customers that provides access to Azure Advisor recommendations, documentation, community forums and billing support only.",
    answers: ["Basic", "Basic support", "Basic support plan"],
    hint: "Free for everyone — no technical support cases",
    difficulty: "medium",
  },
  {
    id: "nts-027",
    prompt: "The Azure support plan providing business-hours access to technical support via email, suited for developers in non-production environments.",
    answers: ["Developer", "Developer support", "Developer support plan"],
    hint: "For developers — email only, business hours",
    difficulty: "medium",
  },
  {
    id: "nts-028",
    prompt: "The Azure support plan providing 24/7 access to technical support by email and phone, with a one-hour response time for critical cases.",
    answers: ["Standard", "Standard support", "Standard support plan"],
    hint: "24/7, phone and email, 1-hour critical response",
    difficulty: "hard",
  },

  // ── Azure networking ────────────────────────────────────────────
  {
    id: "nts-029",
    prompt: "The Azure networking feature that contains a set of inbound and outbound rules used to filter network traffic to and from Azure resources based on IP address, port and protocol.",
    answers: ["Network Security Group", "NSG"],
    hint: "A stateful firewall attached to a subnet or NIC",
    difficulty: "medium",
  },
  {
    id: "nts-030",
    prompt: "The Azure feature that allows virtual networks in the same or different regions to communicate with each other using Microsoft's backbone network, without traffic going over the public internet.",
    answers: ["VNet Peering", "Virtual Network Peering", "Azure VNet Peering"],
    hint: "Connects two VNets so they talk like one",
    difficulty: "medium",
  },

  // ── Networking ──────────────────────────────────────────────────
  {
    id: "nts-031",
    prompt: "An Azure service that creates encrypted IPsec/IKE tunnels over the public internet to connect an Azure virtual network to on-premises networks or other Azure VNets.",
    answers: ["Azure VPN Gateway", "VPN Gateway"],
    hint: "Encrypted tunnel over the internet to Azure",
    difficulty: "easy",
  },
  {
    id: "nts-032",
    prompt: "A network interface that connects to an Azure service using a private IP address from your VNet, removing exposure to the public internet for that service.",
    answers: ["Azure Private Endpoint", "Private Endpoint"],
    hint: "A private door into an Azure service from your VNet",
    difficulty: "medium",
  },
  {
    id: "nts-033",
    prompt: "A managed, cloud-native network security service that protects Azure Virtual Network resources with built-in high availability, stateful packet inspection and centralised policy management.",
    answers: ["Azure Firewall", "Firewall"],
    hint: "Managed Layer 7 firewall — not a security group",
    difficulty: "medium",
  },
  {
    id: "nts-034",
    prompt: "Custom routes in Azure that override default system routes and let you control where traffic is directed — for example, forcing all traffic through a firewall appliance.",
    answers: ["User Defined Routes", "UDR", "Route Table", "Azure Route Table"],
    hint: "Override Azure's default routing with your own rules",
    difficulty: "medium",
  },
  {
    id: "nts-035",
    prompt: "The premium Azure DDoS protection tier that provides enhanced mitigation against volumetric, protocol and application layer attacks for resources in a virtual network, with cost protection and dedicated support.",
    answers: ["Azure DDoS Protection Standard", "DDoS Protection Standard", "DDoS Protection"],
    hint: "The paid tier of DDoS protection — not the default",
    difficulty: "hard",
  },
  {
    id: "nts-036",
    prompt: "An Azure feature that lets you segment a virtual network into smaller address spaces, controlling traffic flow between resources and applying network security groups at a granular level.",
    answers: ["Subnets", "Subnet", "Azure Subnets"],
    hint: "Divides a VNet into smaller address ranges",
    difficulty: "easy",
  },

  // ── Compute ─────────────────────────────────────────────────────
  {
    id: "nts-037",
    prompt: "An Azure service that lets you create and manage a group of identical, load-balanced VMs that automatically increase or decrease in number based on demand or a schedule.",
    answers: ["Virtual Machine Scale Sets", "VMSS", "Azure Virtual Machine Scale Sets"],
    hint: "Auto-scaling group of identical VMs",
    difficulty: "medium",
  },
  {
    id: "nts-038",
    prompt: "A serverless container service that lets you run Docker containers on demand without managing any underlying infrastructure, virtual machines or orchestration platform.",
    answers: ["Azure Container Instances", "ACI"],
    hint: "Run a container — no cluster needed",
    difficulty: "medium",
  },
  {
    id: "nts-039",
    prompt: "Azure virtual machines that use unused Azure compute capacity at up to 90% discount, but can be evicted with 30 seconds' notice when Azure needs the capacity back.",
    answers: ["Azure Spot VMs", "Spot VMs", "Spot Instances", "Azure Spot Instances"],
    hint: "Cheap but interruptible — great for batch jobs",
    difficulty: "medium",
  },
  {
    id: "nts-040",
    prompt: "A cloud-based desktop and application virtualisation service that delivers full Windows desktops and individual apps from Azure to any device over the internet.",
    answers: ["Azure Virtual Desktop", "AVD", "Windows Virtual Desktop", "WVD"],
    hint: "Remote Windows desktop hosted in Azure",
    difficulty: "easy",
  },
  {
    id: "nts-041",
    prompt: "A service providing physical Azure servers dedicated entirely to a single organisation, giving control over the underlying server and supporting bring-your-own-licence (BYOL) scenarios.",
    answers: ["Azure Dedicated Host", "Dedicated Host"],
    hint: "Your own physical Azure server — no shared hardware",
    difficulty: "hard",
  },
  {
    id: "nts-042",
    prompt: "An Azure service for running large-scale parallel and high-performance computing jobs by distributing them across a managed pool of virtual machines.",
    answers: ["Azure Batch", "Batch"],
    hint: "Managed HPC job scheduling on Azure",
    difficulty: "medium",
  },

  // ── Identity ────────────────────────────────────────────────────
  {
    id: "nts-043",
    prompt: "An Azure Active Directory feature that gives an Azure resource (such as a VM or App Service) an automatically managed identity, removing the need to store credentials in code or config.",
    answers: ["Managed Identity", "Azure Managed Identity"],
    hint: "An Azure resource's own identity — no passwords in code",
    difficulty: "medium",
  },
  {
    id: "nts-044",
    prompt: "An Azure service providing customer identity and access management for consumer-facing applications, allowing users to sign in with social accounts like Google, Facebook or Apple.",
    answers: ["Azure AD B2C", "Azure Active Directory B2C", "Azure B2C"],
    hint: "B2C = Business to Consumer identity",
    difficulty: "medium",
  },
  {
    id: "nts-045",
    prompt: "An Azure AD service that provides just-in-time privileged access to Azure resources, requiring approval and time-limited activation for high-privilege roles to reduce standing access.",
    answers: ["Privileged Identity Management", "PIM", "Azure AD PIM"],
    hint: "Just-in-time access for admin roles",
    difficulty: "hard",
  },
  {
    id: "nts-046",
    prompt: "An Azure AD feature that evaluates signals — user, device, location, application — and enforces access policies such as requiring MFA or blocking access based on those conditions.",
    answers: ["Conditional Access", "Azure AD Conditional Access"],
    hint: "If-then access policies based on context signals",
    difficulty: "medium",
  },
  {
    id: "nts-047",
    prompt: "A managed domain service offering domain join, group policy, LDAP and Kerberos/NTLM authentication without deploying or patching domain controllers in the cloud.",
    answers: ["Azure AD Domain Services", "AADDS", "Azure Active Directory Domain Services"],
    hint: "Managed Active Directory — no DC VMs to manage",
    difficulty: "hard",
  },
  {
    id: "nts-048",
    prompt: "The Azure authorization system built on Resource Manager that provides fine-grained access management using roles assigned to users, groups or service principals at a specific scope.",
    answers: ["Role-Based Access Control", "RBAC", "Azure RBAC"],
    hint: "Who can do what to which resource",
    difficulty: "easy",
  },

  // ── Storage ─────────────────────────────────────────────────────
  {
    id: "nts-049",
    prompt: "A fully managed cloud file share service accessible over SMB and NFS protocols, usable as a drop-in replacement for on-premises file servers or as a persistent volume for containers.",
    answers: ["Azure Files", "Azure File Storage", "Azure File Shares"],
    hint: "Cloud file shares over SMB or NFS",
    difficulty: "easy",
  },
  {
    id: "nts-050",
    prompt: "An Azure storage service that holds large numbers of messages accessible from anywhere via authenticated HTTP or HTTPS calls, typically used to decouple application components.",
    answers: ["Azure Queue Storage", "Queue Storage"],
    hint: "Simple message queue — not a full broker like Service Bus",
    difficulty: "medium",
  },
  {
    id: "nts-051",
    prompt: "The Azure managed disk tier that uses SSD-based storage to deliver consistent high performance and low latency for I/O-intensive workloads such as databases and transaction processing.",
    answers: ["Premium SSD"],
    hint: "SSD managed disks for production databases",
    difficulty: "easy",
  },
  {
    id: "nts-052",
    prompt: "The highest-performance Azure managed disk tier, offering sub-millisecond latency and up to 160,000 IOPS per disk — designed for the most demanding SAP HANA and top-tier database workloads.",
    answers: ["Ultra Disk", "Azure Ultra Disk"],
    hint: "The extreme-performance managed disk option",
    difficulty: "hard",
  },
  {
    id: "nts-053",
    prompt: "A massively scalable analytics data store built on Blob Storage that adds a hierarchical namespace and fine-grained ACLs, optimised for big data analytics workloads.",
    answers: ["Azure Data Lake Storage Gen2", "ADLS Gen2", "Azure Data Lake Storage", "ADLS"],
    hint: "Blob Storage + hierarchical namespace = analytics-ready",
    difficulty: "hard",
  },
  {
    id: "nts-054",
    prompt: "An Azure NoSQL storage service that stores structured, schema-less data as key-attribute pairs, designed for fast access to large amounts of non-relational data.",
    answers: ["Azure Table Storage", "Table Storage"],
    hint: "Key-value NoSQL store — simpler and cheaper than Cosmos DB",
    difficulty: "medium",
  },

  // ── Governance ──────────────────────────────────────────────────
  {
    id: "nts-055",
    prompt: "An Azure service that packages together role assignments, policy assignments and resource templates into a reusable definition that can be applied consistently across subscriptions.",
    answers: ["Azure Blueprints", "Blueprints"],
    hint: "A repeatable pattern of policies, roles and resources",
    difficulty: "hard",
  },
  {
    id: "nts-056",
    prompt: "An Azure feature that prevents accidental deletion or modification of resources. It has two modes: one that blocks deletion only, and one that allows only read operations.",
    answers: ["Resource Locks", "Azure Resource Locks"],
    hint: "Prevents accidental changes or deletion",
    difficulty: "easy",
  },
  {
    id: "nts-057",
    prompt: "Key-value pairs you attach to Azure resources and resource groups to logically organise them, support cost allocation to departments and enable automation based on metadata.",
    answers: ["Tags", "Resource Tags", "Azure Tags"],
    hint: "Metadata labels for organising and billing resources",
    difficulty: "easy",
  },
  {
    id: "nts-058",
    prompt: "The Azure tool for monitoring, analysing and controlling your cloud spend. It lets you set budgets, create cost alerts and view spending trends across subscriptions and resource groups.",
    answers: ["Azure Cost Management", "Cost Management", "Azure Cost Management and Billing"],
    hint: "Track and control your Azure bill",
    difficulty: "easy",
  },
  {
    id: "nts-059",
    prompt: "The Azure container for organising related resources that share the same lifecycle, permissions and policies — the fundamental unit of deployment and management in Azure.",
    answers: ["Resource Group", "Azure Resource Group"],
    hint: "A logical container for Azure resources",
    difficulty: "easy",
  },

  // ── Monitoring ──────────────────────────────────────────────────
  {
    id: "nts-060",
    prompt: "The comprehensive Azure monitoring platform that collects metrics and logs from Azure resources, on-premises systems and other clouds, enabling alerting, dashboards and automated actions.",
    answers: ["Azure Monitor", "Monitor"],
    hint: "The umbrella monitoring service — everything flows through here",
    difficulty: "easy",
  },
  {
    id: "nts-061",
    prompt: "A workspace-based tool inside Azure Monitor used to query and analyse log data using the Kusto Query Language (KQL), aggregating logs from VMs, containers and Azure services.",
    answers: ["Azure Log Analytics", "Log Analytics", "Log Analytics workspace"],
    hint: "Write KQL queries to analyse logs",
    difficulty: "medium",
  },
  {
    id: "nts-062",
    prompt: "An Azure Monitor feature that instruments web applications to automatically detect performance anomalies, track requests, dependencies and exceptions, and provide live usage analytics.",
    answers: ["Application Insights", "Azure Application Insights"],
    hint: "APM for live web apps — tracks requests, failures and latency",
    difficulty: "medium",
  },
  {
    id: "nts-063",
    prompt: "A personalised Azure dashboard that shows information about current service issues, planned maintenance and health advisories that could affect your specific Azure resources.",
    answers: ["Azure Service Health", "Service Health"],
    hint: "Shows Azure outages that affect YOUR resources specifically",
    difficulty: "easy",
  },
  {
    id: "nts-064",
    prompt: "An Azure service providing network diagnostic tools including IP flow verify, connection troubleshoot, packet capture and topology views for resources within a virtual network.",
    answers: ["Azure Network Watcher", "Network Watcher"],
    hint: "Diagnose connectivity issues inside your VNet",
    difficulty: "medium",
  },

  // ── Security ────────────────────────────────────────────────────
  {
    id: "nts-065",
    prompt: "A cloud security posture management (CSPM) and workload protection platform that provides unified security management and advanced threat protection across Azure, on-premises and multi-cloud environments.",
    answers: ["Microsoft Defender for Cloud", "Defender for Cloud", "Azure Security Center"],
    hint: "Formerly Azure Security Center — rates your secure score",
    difficulty: "medium",
  },
  {
    id: "nts-066",
    prompt: "A cloud-native SIEM and SOAR solution that provides intelligent security analytics and threat intelligence across the enterprise, enabling threat detection, investigation and automated response.",
    answers: ["Microsoft Sentinel", "Azure Sentinel", "Sentinel"],
    hint: "Cloud-native SIEM — collects signals, hunts threats, automates response",
    difficulty: "medium",
  },
  {
    id: "nts-067",
    prompt: "A Microsoft Defender for Cloud feature that reduces VM attack surface by locking down inbound ports and only opening them for specific users for a limited, defined time window.",
    answers: ["Just-in-Time VM Access", "JIT", "Just-in-Time access", "JIT VM Access"],
    hint: "Only opens RDP/SSH ports when specifically requested",
    difficulty: "hard",
  },
  {
    id: "nts-068",
    prompt: "The Azure Firewall tier that adds signature-based intrusion detection and prevention (IDPS), TLS inspection, URL filtering and web category filtering to the standard firewall capabilities.",
    answers: ["Azure Firewall Premium", "Firewall Premium"],
    hint: "Firewall + IDPS + TLS inspection",
    difficulty: "hard",
  },
  {
    id: "nts-069",
    prompt: "An Azure AD feature that automatically detects suspicious sign-in behaviour — such as logins from unfamiliar locations or infected devices — and can block or challenge those sign-ins.",
    answers: ["Azure AD Identity Protection", "Identity Protection", "Azure Identity Protection"],
    hint: "Detects risky sign-ins and compromised identities automatically",
    difficulty: "hard",
  },

  // ── Additional services ─────────────────────────────────────────
  {
    id: "nts-070",
    prompt: "A big data streaming and event ingestion service capable of receiving and processing millions of events per second from applications, devices and telemetry streams.",
    answers: ["Azure Event Hubs", "Event Hubs"],
    hint: "High-throughput event streaming — like Kafka on Azure",
    difficulty: "medium",
  },
  {
    id: "nts-071",
    prompt: "A serverless event routing service that enables reactive, event-driven architectures by routing events from Azure services or custom sources to subscriber endpoints using a publish-subscribe model.",
    answers: ["Azure Event Grid", "Event Grid"],
    hint: "Routes discrete events to handlers — not a stream",
    difficulty: "medium",
  },
  {
    id: "nts-072",
    prompt: "A fully managed in-memory data store based on the open-source Redis engine, used to dramatically improve application performance by caching frequently accessed data.",
    answers: ["Azure Cache for Redis", "Azure Redis Cache", "Cache for Redis"],
    hint: "In-memory caching layer — dramatically speeds up read-heavy apps",
    difficulty: "easy",
  },
  {
    id: "nts-073",
    prompt: "A cloud-based ETL and data integration service that allows you to create, schedule and orchestrate data pipelines that move and transform data between disparate data stores.",
    answers: ["Azure Data Factory", "ADF"],
    hint: "Cloud ETL — move and transform data between stores",
    difficulty: "medium",
  },
  {
    id: "nts-074",
    prompt: "An analytics service that brings together big data and data warehousing into a single platform, allowing you to query data using serverless SQL pools or dedicated SQL pools.",
    answers: ["Azure Synapse Analytics", "Synapse Analytics", "Azure Synapse"],
    hint: "Data warehouse + big data analytics in one service",
    difficulty: "medium",
  },
  {
    id: "nts-075",
    prompt: "A non-HTTP Layer 4 load balancing service that distributes inbound TCP and UDP traffic across healthy VM instances within a virtual network, operating at the transport layer.",
    answers: ["Azure Load Balancer", "Load Balancer"],
    hint: "Layer 4 TCP/UDP load balancing — not HTTP/HTTPS aware",
    difficulty: "medium",
  },
  {
    id: "nts-076",
    prompt: "Physically separate datacenter locations within an Azure region, each with independent power, cooling and networking, providing protection against single datacenter failures.",
    answers: ["Availability Zones", "Azure Availability Zones"],
    hint: "Three isolated locations within one Azure region",
    difficulty: "easy",
  },
  {
    id: "nts-077",
    prompt: "Two Azure regions within the same geography automatically paired by Microsoft for disaster recovery, ensuring replication and update sequencing to reduce the chance of both being down simultaneously.",
    answers: ["Region Pairs", "Azure Region Pairs", "Paired Regions", "Region Pair"],
    hint: "UK South pairs with UK West — one region protects the other",
    difficulty: "medium",
  },
  {
    id: "nts-078",
    prompt: "An Azure service that extends Azure management, governance and services to any infrastructure — on-premises servers, other clouds or edge locations — using a single control plane.",
    answers: ["Azure Arc", "Arc"],
    hint: "Manage non-Azure resources as if they were in Azure",
    difficulty: "medium",
  },
  {
    id: "nts-079",
    prompt: "A central hub of tools for discovering, assessing and migrating on-premises servers, databases and web applications to Azure, providing readiness reports and cost estimates.",
    answers: ["Azure Migrate", "Migrate"],
    hint: "The starting point for any on-premises to Azure migration",
    difficulty: "easy",
  },
  {
    id: "nts-080",
    prompt: "An Azure disaster recovery service that replicates virtual machines and physical servers from a primary site to a secondary location, enabling orchestrated failover with near-zero RPO.",
    answers: ["Azure Site Recovery", "Site Recovery", "ASR"],
    hint: "Replicates VMs to a secondary region for DR failover",
    difficulty: "medium",
  },
];

export default QUESTIONS;
